### ISSUE TITLE
Vergeet Progressive Enhancement niet

### ISSUE THREAD

**Issue by krijnhoetmer** [r20222/your-tribe-for-life-squad-page#35]
Hoe werkt dit alles zonder JS bijvoorbeeld?

https://github.com/r20222/your-tribe-for-life-squad-page/blob/a498c8e6986ead99e3de03d61e64e06f6f6e3c06/src/lib/slices/Members/index.svelte#L19-L23

**Comment by RickVellingaa** [comment]
Als dit op een manier makkelijker kan hoor ik het wel haha
